spring: 
  
  profiles.active: jpa-dev, db-local-hsqldb, uploads-dev, mixednutz_base, twitter, discord, aws-local
#  profiles.active: jpa-dev, db-local-hsqldb-file, uploads-dev, twitter, aws-local

  main:
    allow-circular-references: true

  data:
    rest:
      basePath: /api

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
        debug: true

  web.resources.addMappings: false

site.settings.uniqueId: 1

rememberMe:
  key: ${REMEMBER_ME_KEY:changeme}
  tokenValiditySeconds: 2592000

mixednutz:
  network-info:
    id: andrewfestadotcom
    host-name: andrewfesta.com
    display-name: AndrewFesta.com

  email:
    display-name: AndrewFesta.com
    no-reply: noreply@andrewfesta.com
    log-to: andy_festa@yahoo.com

#ads-txt: "classpath:static/ads.txt"

server.servlet.session.timeout: 60m
    
logging:
  level: 
    root: WARN
    org.springframework.web: INFO
#    org.hibernate.SQL: DEBUG
    net.mixednutz.app.server: INFO
  file:
    path: .
    name: mixednutz-app-server.log

    
---
spring:
  config.activate.on-profile: uploads-dev
  
---
spring:
  config.activate.on-profile: uploads-prod
  
photoDirectory: ${PHOTO_DIRECTORY}

mixednutz:
  aws.photosBucket: andrewfesta-com-photos

---
# Optionally link up with other Mixednutz instance
spring:
  config.activate.on-profile: mixednutz_base
  
  
mixednutz:
  social: 
    mixednutz:
      base-url: https://mixednutz.net
      client-id: mixednutzjavaapi
      client-secret: mySecret
      scope: timeline

---
# Optionally link up with Twitter
spring:
  config.activate.on-profile: twitter
  
mixednutz:
  social: 
    twitter:
      consumer-key: ${TWITTER_CONSUMER_KEY}
      consumer-secret: ${TWITTER_CONSUMER_SECRET}
      
---
# Optionally link up with Discord
spring:
  config.activate.on-profile: discord
  
mixednutz:
  social: 
    discord:
      token: ${DISCORD_TOKEN}
      default-channel-id: ${DISCORD_CHANNEL_ID}

---
spring:
  config.activate.on-profile: ssl
  
server:
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
  ssl:
    key-store: "${KEYSTORE_FILE}"
    key-store-type: "${KEYSTORE_TYPE}"
    key-store-password: "${KEYSTORE_PASS}"
  
#keystore:
#  file: ${KEYSTORE_FILE}
#  pass.file: ${KEYSTORE_PASS_FILE}
#  type: ${KEYSTORE_TYPE}
      
---
spring:
  config.activate.on-profile: jpa-dev
  
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: update
    properties: 
      hibernate:
        hbm2ddl.auto: update
      
---
spring:
  config.activate.on-profile: jpa-prod
  
  jpa:
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: update
      
---
spring:
  config.activate.on-profile: db-docker-mysql
  # This profile is for Docker containers  the database login configuration is abstracted out to the enviroment.

  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource: 
    platform: mysql
    url: jdbc:mysql://${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/${MYSQL_DB_NAME}
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
    testOnBorrow: true
    testWhileIdle: true
    validationQuery: SELECT 1
    removeAbandoned: true
    initialSize: 100
    
---
spring:
  config.activate.on-profile: db-local-mysql
  # This profile is for Andy's local environment
  
---
spring:
  config.activate.on-profile: db-local-hsqldb
  # This profile is for in-memory database
  
  jpa: 
    properties: 
      hibernate: 
        dialect: net.mixednutz.app.server.extensions.hibernate.CustomHsqlDialect

---
spring:
  config.activate.on-profile: db-local-hsqldb-file
  # This profile is for file database

  #datasource:
  #  url: jdbc:hsqldb:file:data/mydb
  #  username: SA
  #  password: test
  #  driverClassName: org.hsqldb.jdbc.JDBCDriver
  
  jpa: 
    properties: 
      hibernate: 
        dialect: net.mixednutz.app.server.extensions.hibernate.CustomHsqlDialect
---
spring:
  config.activate.on-profile: aws-local
  # This profile is for Andy's local environment
  
cloud:
  aws:
    region.static: us-east-1
    stack.auto: false
