spring: 
  
  profiles.active: jpa-dev, db-local-hsqldb, uploads-dev, mixednutz_base, twitter, aws-local
#  profiles.active: jpa-dev, db-local-hsqldb-file, uploads-dev, twitter, aws-local
  
  data:
    rest:
      basePath: /api

site.settings.uniqueId: 1

mixednutz:
  network-info:
    id: andrewfestadotcom
    host-name: andrewfesta.com
    display-name: AndrewFesta.com
    
logging:
  level: 
    root: WARN
    org.springframework.web: INFO
#    org.hibernate.SQL: DEBUG
    net.mixednutz.app.server: INFO
  file: logs/mixednutz-app-server.log

    
---
spring:
  profiles: uploads-dev
  
---
spring:
  profiles: uploads-prod
  
photoDirectory: ${PHOTO_DIRECTORY}

mixednutz:
  aws.photosBucket: andrewfesta-com-photos

---
# Optionally link up with other Mixednutz instance
spring:
  profiles: mixednutz_base
  
  
mixednutz:
  social: 
    mixednutz:
      base-url: https://mixednutz.net
      client-id: mixednutzjavaapi
      client-secret: mySecret
      scope: timeline

---
# Optionally link up with Twitter
spring:
  profiles: twitter
  
mixednutz:
  social: 
    twitter:
      consumer-key: ${TWITTER_CONSUMER_KEY}
      consumer-secret: ${TWITTER_CONSUMER_SECRET}
      
---
spring:
  profiles: ssl
  
server:
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
  ssl:
    key-store: ${KEYSTORE_FILE}
    key-store-type: ${KEYSTORE_TYPE}
    key-password: ${KEYSTORE_PASS} 
  
#keystore:
#  file: ${KEYSTORE_FILE}
#  pass.file: ${KEYSTORE_PASS_FILE}
#  type: ${KEYSTORE_TYPE}
      
---
spring:
  profiles: jpa-dev
  
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: update
    properties: 
      hibernate:
        hbm2ddl.auto: update
      
---
spring:
  profiles: jpa-prod
  
  jpa:
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: update
      
---
spring:
  profiles: db-docker-mysql
  # This profile is for Docker containers  the database login configuration is abstracted out to the enviroment.

  datasource: 
    platform: mysql
    url: jdbc:mysql://${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/${MYSQL_DB_NAME}
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
    testOnBorrow: true
    testWhileIdle: true
    validationQuery: SELECT 1
    removeAbandoned: true
    initialSize: 100
    
---
spring:
  profiles: db-local-mysql
  # This profile is for Andy's local environment
  
---
spring:
  profiles: db-local-hsqldb
  # This profile is for in-memory database
  
  jpa: 
    properties: 
      hibernate: 
        dialect: net.mixednutz.app.server.extensions.hibernate.CustomHsqlDialect

---
spring:
  profiles: db-local-hsqldb-file
  # This profile is for file database

  #datasource:
  #  url: jdbc:hsqldb:file:data/mydb
  #  username: SA
  #  password: test
  #  driverClassName: org.hsqldb.jdbc.JDBCDriver
  
  jpa: 
    properties: 
      hibernate: 
        dialect: net.mixednutz.app.server.extensions.hibernate.CustomHsqlDialect
---
spring:
  profiles: aws-local
  # This profile is for Andy's local environment
  
cloud:
  aws:
    region.static: us-east-1
    stack.auto: false
