spring: 
  
  profiles.active: jpa-dev, mixednutz_base, twitter

site.settings.uniqueId: 1

---
# Optionally link up with other Mixednutz instance
spring:
  profiles: mixednutz_base
  
  
mixednutz:
  social: 
    mixednutz:
      base-url: https://mixednutz.net
      client-id: mixednutzjavaapi
      client-secret: mySecret
      scope: timeline

---
# Optionally link up with Twitter
spring:
  profiles: twitter
  
mixednutz:
  social: 
    twitter:
      consumer-key: ${TWITTER_CONSUMER_KEY}
      consumer-secret: ${TWITTER_CONSUMER_SECRET}
      
---
spring:
  profiles: ssl
  
server:
  ssl:
    key-store: ${KEYSTORE_FILE}
    key-store-type: ${KEYSTORE_TYPE}
    key-password: ${KEYSTORE_PASS} 
  
#keystore:
#  file: ${KEYSTORE_FILE}
#  pass.file: ${KEYSTORE_PASS_FILE}
#  type: ${KEYSTORE_TYPE}
      
---
spring:
  profiles: jpa-dev
  
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: create
      
---
spring:
  profiles: jpa-prod
  
  jpa:
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
      ddl-auto: update
      
---
spring:
  profiles: db-docker-mysql
  # This profile is for Docker containers  the database login configuration is abstracted out to the enviroment.
  
  datasource:
    url: jdbc:mysql://${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/${MYSQL_DB_NAME}
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
    testOnBorrow: true
    testWhileIdle: true
    validationQuery: SELECT 1
    removeAbandoned: true
    initialSize: 100
    
---
spring:
  profiles: db-local-mysql
  # This profile is for Andy's local environment
